version: 2.1

# --- Anchor alias ---- #
alias:
# ---- Jobs filters ---- #
  - &filters_only_dev
    branches:
      only: dev
    tags:
      ignore: /.*/
  - &filters_only_branch
    branches:
      ignore:
        - dev
    tags:
      ignore: /.*/
  - &filters_only_tags
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

orbs:
  # docs: https://circleci.com/developer/orbs/orb/habx/node
  node: habx/node@0.13.2
# --- END --- #
# --------------------------------------------------- #
# -------------- DEFINE YOUR WORKFLOW --------------- #
# --------------------------------------------------- #
workflows:
  tests:
    jobs:
      - node/lint:
          filters:
            <<: *filters_only_branch
      - node/build:
          filters:
            <<: *filters_only_branch
  dev:
    jobs:
      - node/lint:
          filters:
            <<: *filters_only_dev
      - node/build:
          filters:
            <<: *filters_only_dev
  release:
    jobs:
      - node/build:
          filters:
            <<: *filters_only_tags